### ISSUE TITLE
This pipeline failed to do with virus-containing polyproteins

### ISSUE THREAD

**Issue by NailouZhang** [PombertLab/A2GB#7]
Hi,
When I try to deal with viruses (e.g. ZIKV, DENGUE, ) containing polyproteins, which are coded by one CDS but were processed into many proteins at the post-transcription stage.

I want to get the feature tbl like https://www.ncbi.nlm.nih.gov/nuccore/NC_012532.1
#----------------------------------------------------------------------------------------------#
# ZIKV
     5'UTR           1..106
     gene            107..10366
                     /gene="POLY"
                     /locus_tag="ZIKV_gp1"
                     /db_xref="GeneID:7751225"
     CDS             107..10366
                     /gene="POLY"
                     /locus_tag="ZIKV_gp1"
                     /codon_start=1
                     /product="polyprotein"
                     /protein_id="YP_002790881.1"
                     /db_xref="GeneID:7751225"
      *mat_peptide     107..472*
                   /gene="POLY"
                     /locus_tag="ZIKV_gp1"
                     /product="anchored capsid protein ancC"
                     /protein_id="YP_009227206.1"
     mat_peptide     107..418
                     /gene="POLY"
                     /locus_tag="ZIKV_gp1"
                     /product="capsid protein C"
                     /protein_id="YP_009227196.1"
     mat_peptide     473..976
                     /gene="POLY"
                     /locus_tag="ZIKV_gp1"
                     /product="membrane glycoprotein precursor prM"
                     /protein_id="YP_009227197.1"
     mat_peptide     473..751
                     /gene="POLY"
                     /locus_tag="ZIKV_gp1"
                     /product="protein pr"
                     /protein_id="YP_009227207.1"
     mat_peptide     752..976
                     /gene="POLY"
                     /locus_tag="ZIKV_gp1"
                     /product="membrane glycoprotein M"
                     /protein_id="YP_009227208.1"
     mat_peptide     977..2476
                     /gene="POLY"
                     /locus_tag="ZIKV_gp1"
                     /product="envelope protein E"
                     /protein_id="YP_009227198.1"
     mat_peptide     2477..3532
                     /gene="POLY"
                     /locus_tag="ZIKV_gp1"
                     /product="nonstructural protein NS1"
                     /protein_id="YP_009227199.1"
#----------------------------------------------------------------------------------------------#
when I finished A2GB pipeline, I only get gene feature belong to CDS with information about mat_peptide ,
#----------------------------------------------------------------------------------------------#
# only CDS region
     gene            107..10366
                     /gene="POLY"
                     /locus_tag="ZIKV_gp1"
                     /db_xref="GeneID:7751225"
     CDS             107..10366
                     /gene="POLY"
                     /locus_tag="ZIKV_gp1"
                     /codon_start=1
                     /product="polyprotein"
                     /protein_id="YP_002790881.1"
                     /db_xref="GeneID:7751225"
#----------------------------------------------------------------------------------------------#

### So, could you be nice help me to add this to final tbl files with scripts from InterproScan software?

**Comment by Pombert-JF** [comment]
Hi Nailou,

That is an interesting problem. We built the pipeline for large eukaryote genomes so you might be better off using something built specifically for viruses given the differences with eukaryote genomes. A quick search for virus annotation pipelines should return a few tools built for viruses.

With that said it should be straightforward to write something that creates a .tbl file with mat_peptides from interproscan searches, but we would need an input example.

Looking at the structure of the .tbl files for viruses, it is quite different in that there is no mRNA, the mat_peptides each have their own unique protein_id tag, and there is a 5’/3’ UTR per polyprotein. I'm not sure if the 5’/3’ UTR are required for NCBI deposition of viral genomes, but if so you would need a list of the polyproteins and their 5’/3’ UTR to help generate the .tbl files.

BTW, Artemis supports mat_peptides and can save directly as .tbl files with the FIle > Sequin Table Format. For small genomes like this, Artemis might be more interesting to you.

**Comment by NailouZhang** [comment]
Hi, 
Thanks for your advice.
I found https://github.com/ncbi/vadr may resolve this issue. It annotates viruses based on reference viral genomes.
