### ISSUE TITLE
question about the ApolloGFF3toEMBL.pl script

### ISSUE THREAD

**Issue by longzhangnation** [PombertLab/A2GB#8]
Hi, thanks for developing A2GB software, it is very useful. I have my genome annotated by Evidencemodeler. The gff3 file has 'mRNA' attribute. Usually one gene has more than one 'mRNA' attribute. ApolloGFF3toEMBL.pl combines all cds/exons sequences in a gene, and the translated gene protein sequences contains stop codons in it because of the combining. So I am writing to ask if any solution to solve this problem? One gene could have different annotation structure rather than by combining them? Thanks.

**Comment by Pombert-JF** [comment]
The A2GB pipeline currently does not support isoforms (really should implement support for it but have been swamped with other things). I'd recommend looking at funnanotate [fun](https://github.com/nextgenusfs/funannotate) to see if it fits your needs.

Best,
JF
